### ISSUE TITLE
[BUG] My lesson skipper keeps on saying im already skipping a lesson ever though im not.

### ISSUE THREAD

**Issue by NinTheCoolGuy** [cupiditys/iReady-Overload#174]
When I accidentally pressed skip current lesson on the lesson page it started to say I'm already skipping a lesson even though im trying to skip a different lesson.

![image](https://user-images.githubusercontent.com/90517061/153084081-b5745755-3952-48fd-8f9e-d1ebcc410bd6.png)

**Comment by Supamariobros** [comment]
Yes, I think this is normal. You will have to go back to the main menu click skip again (if that pops up it's ok) and then it should be fixed and skipped. If it is a test you should be able to set your score. Some lessons may not be able to be skipped tho. For example cold read etc. As so as he mentioned so that may be your problem. I'm working on very little info.

**Comment by NinTheCoolGuy** [comment]
Sorry but the problem is still not solved. When I boot up iready it seems like its normal then i go to skip a lesson then all of a sudden when i try to exit out of the lesson it says that there is something wrong and when i try to click the arrow it doesnt work.  And before that it would appear the overload is fine when i boot up iready but when i try to get the overload to skip the lesson it answers with the image posted earlier in my original post.

**Comment by cupiditys** [comment]
> Sorry but the problem is still not solved. When I boot up iready it seems like its normal then i go to skip a lesson then all of a sudden when i try to exit out of the lesson it says that there is something wrong and when i try to click the arrow it doesnt work. And before that it would appear the overload is fine when i boot up iready but when i try to get the overload to skip the lesson it answers with the image posted earlier in my original post.

send a video

**Comment by cupiditys** [comment]
> @cupiditys
> 
>  iready.shit.mp4

first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work

**Comment by NinTheCoolGuy** [comment]
> > @cupiditys
> > iready.shit.mp4
> 
> first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work

First of all , lol its bad resolution cause i dont want anybody to see my name and second of all i did do that bro it keeps on saying that im already skipping a lesson even though im not.

**Comment by cupiditys** [comment]
> > > @cupiditys
> > > iready.shit.mp4
> > 
> > 
> > first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work
> 
> First of all , lol its bad resolution cause i dont want anybody to see my name and second of all i did do that bro it keeps on saying that im already skipping a lesson even though im not.

idfk bro I can’t even see the alert

**Comment by NinTheCoolGuy** [comment]
> > > > @cupiditys
> > > > iready.shit.mp4
> > > 
> > > 
> > > first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work
> > 
> > 
> > First of all , lol its bad resolution cause i dont want anybody to see my name and second of all i did do that bro it keeps on saying that im already skipping a lesson even though im not.
> 
> idfk bro I can’t even see the alert

but it showed the alert tho bruh but anyways how can i fix this?

**Comment by cupiditys** [comment]
> > > > > @cupiditys
> > > > > iready.shit.mp4
> > > > 
> > > > 
> > > > first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work
> > > 
> > > 
> > > First of all , lol its bad resolution cause i dont want anybody to see my name and second of all i did do that bro it keeps on saying that im already skipping a lesson even though im not.
> > 
> > 
> > idfk bro I can’t even see the alert
> 
> but it showed the alert tho bruh but anyways how can i fix this?

record a normal video so I can actually see what’s happening

**Comment by NinTheCoolGuy** [comment]
> > > > > > @cupiditys
> > > > > > iready.shit.mp4
> > > > > 
> > > > > 
> > > > > first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work
> > > > 
> > > > 
> > > > First of all , lol its bad resolution cause i dont want anybody to see my name and second of all i did do that bro it keeps on saying that im already skipping a lesson even though im not.
> > > 
> > > 
> > > idfk bro I can’t even see the alert
> > 
> > 
> > but it showed the alert tho bruh but anyways how can i fix this?
> 
> record a normal video so I can actually see what’s happening

Ok i will do it when the extension gets update and when it does ill show u.

**Comment by NinTheCoolGuy** [comment]
> > > > > > > @cupiditys
> > > > > > > iready.shit.mp4
> > > > > > 
> > > > > > 
> > > > > > first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work
> > > > > 
> > > > > 
> > > > > First of all , lol its bad resolution cause i dont want anybody to see my name and second of all i did do that bro it keeps on saying that im already skipping a lesson even though im not.
> > > > 
> > > > 
> > > > idfk bro I can’t even see the alert
> > > 
> > > 
> > > but it showed the alert tho bruh but anyways how can i fix this?
> > 
> > 
> > record a normal video so I can actually see what’s happening
> 
> Ok i will do it when the extension gets update and when it does ill show u.

@cupiditys  here you g

https://user-images.githubusercontent.com/90517061/153724408-6004f4a2-dcad-48d8-afec-2223ac2543b1.mp4

o

**Comment by cupiditys** [comment]
> > > > > > > > @cupiditys
> > > > > > > > iready.shit.mp4
> > > > > > > 
> > > > > > > 
> > > > > > > first off wtf is that resolution bruh and second you have to **open** the lesson before skipping or else it wont work
> > > > > > 
> > > > > > 
> > > > > > First of all , lol its bad resolution cause i dont want anybody to see my name and second of all i did do that bro it keeps on saying that im already skipping a lesson even though im not.
> > > > > 
> > > > > 
> > > > > idfk bro I can’t even see the alert
> > > > 
> > > > 
> > > > but it showed the alert tho bruh but anyways how can i fix this?
> > > 
> > > 
> > > record a normal video so I can actually see what’s happening
> > 
> > 
> > Ok i will do it when the extension gets update and when it does ill show u.
> 
> @cupiditys here you g
> 
>  here.mp4 
> 
> o

ok bro ur literally just trolling
