### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Schsway** [cupiditys/iReady-Overload#191]
skipping lesson is not working 

proof: 

![image](https://user-images.githubusercontent.com/99513595/153685127-4244ab78-1238-43f4-86b3-30e51b0cc6fe.png)

![image](https://user-images.githubusercontent.com/99513595/153685144-b51aa3cb-198c-4c0d-bd6b-fe6be2c6634b.png)

![image](https://user-images.githubusercontent.com/99513595/153685161-4176b1a1-29fd-46b7-b564-20298f0d5c5d.png)

**Comment by Schsway** [comment]
if it works for someone else let me know might be my pc

**Comment by cupiditys** [comment]
well thats just amazing

**Comment by Schsway** [comment]
> well thats just amazing

Lmao take ur time to fix it i just wanted to make sure u know whats going on 

btw: I love u ur a life savior

**Comment by cupiditys** [comment]
good news and bad news
good news is it still works
bad news just not in the extension

**Comment by comradeduck** [comment]
It’s not you either it’s me too

**Comment by cupiditys** [comment]
fixed

**Comment by SenpiEcwipse** [comment]
ya im still having problems i reinstalled it and it did nothin but it works for math perfecly fine but not readinf hop u can fix it <3 :)
